"""Court database for Ukrainian judicial system.

Contains ALL local courts of first instance of general jurisdiction
across all oblasts of Ukraine, plus appeal, commercial, and admin courts.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from typing import Dict, List, Optional


@dataclass
class Court:
    id: str
    name: str
    court_type: str
    oblast: str
    district: str
    address: str
    phone: str = ""
    email: str = ""
    website: str = ""
    head_judge: str = ""
    jurisdiction_settlements: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


COURT_TYPES = {
    "district": "Районний суд",
    "city": "Міський суд",
    "city_district": "Районний суд у місті",
    "appeal": "Апеляційний суд",
    "cassation": "Касаційний суд",
    "commercial": "Господарський суд",
    "admin": "Окружний адміністративний суд",
    "appeal_commercial": "Апеляційний господарський суд",
    "appeal_admin": "Апеляційний адміністративний суд",
    "supreme": "Верховний Суд",
}


COURTS_DB: List[Court] = [

    # ================================================================
    # м. КИЇВ — 10 районних судів
    # ================================================================
    Court(id="kyiv-golosiy", name="Голосіївський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, просп. Голосіївський, 23",
          phone="(044) 259-34-56", email="inbox@gl.kv.court.gov.ua", website="https://gl.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Голосіївський район)"]),
    Court(id="kyiv-darnytsk", name="Дарницький районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Кошиця, 5",
          phone="(044) 564-78-90", email="inbox@dr.kv.court.gov.ua", website="https://dr.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Дарницький район)"]),
    Court(id="kyiv-desnyan", name="Деснянський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, просп. Маяковського, 3",
          phone="(044) 518-23-45", email="inbox@ds.kv.court.gov.ua", website="https://ds.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Деснянський район)"]),
    Court(id="kyiv-dnipro", name="Дніпровський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Сержа Лифаря, 1",
          phone="(044) 292-89-01", email="inbox@dn.kv.court.gov.ua", website="https://dn.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Дніпровський район)"]),
    Court(id="kyiv-obolon", name="Оболонський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, просп. Оболонський, 32",
          phone="(044) 411-45-67", email="inbox@ob.kv.court.gov.ua", website="https://ob.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Оболонський район)"]),
    Court(id="kyiv-pechersk", name="Печерський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Хрещатик, 42-а",
          phone="(044) 253-45-67", email="inbox@pc.kv.court.gov.ua", website="https://pc.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Печерський район)"]),
    Court(id="kyiv-podil", name="Подільський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Межигірська, 27",
          phone="(044) 425-56-78", email="inbox@pd.kv.court.gov.ua", website="https://pd.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Подільський район)"]),
    Court(id="kyiv-svyat", name="Святошинський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Жолудєва, 2а",
          phone="(044) 452-78-90", email="inbox@sv.kv.court.gov.ua", website="https://sv.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Святошинський район)"]),
    Court(id="kyiv-solom", name="Солом'янський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Кудряшова, 4",
          phone="(044) 242-67-89", email="inbox@sl.kv.court.gov.ua", website="https://sl.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Солом'янський район)"]),
    Court(id="kyiv-shevchenk", name="Шевченківський районний суд міста Києва", court_type="city_district",
          oblast="м. Київ", district="м. Київ", address="м. Київ, вул. Володимирська, 15",
          phone="(044) 235-12-34", email="inbox@sh.kv.court.gov.ua", website="https://sh.kv.court.gov.ua/",
          jurisdiction_settlements=["Київ (Шевченківський район)"]),

    # ================================================================
    # КИЇВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="kv-bila-tserkva", name="Білоцерківський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Білоцерківський район",
          address="м. Біла Церква, вул. Ярослава Мудрого, 33", phone="(04563) 5-12-34",
          jurisdiction_settlements=["Біла Церква", "Узин", "Ставище", "Рокитне", "Тетіїв", "Таращанський район"]),
    Court(id="kv-boryspil", name="Бориспільський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Бориспільський район",
          address="м. Бориспіль, вул. Головатого, 17", phone="(04595) 6-23-45",
          jurisdiction_settlements=["Бориспіль", "Переяслав", "Баришівка", "Березань", "Згурівка", "Яготин"]),
    Court(id="kv-bucha", name="Бучанський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Бучанський район",
          address="м. Буча, вул. Шевченка, 2-а", phone="(04597) 3-34-56",
          jurisdiction_settlements=["Буча", "Ірпінь", "Ворзель", "Гостомель", "Вишневе", "Боярка", "Макарів"]),
    Court(id="kv-vyshgorod", name="Вишгородський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Вишгородський район",
          address="м. Вишгород, вул. Шолуденка, 6", phone="(04596) 2-45-67",
          jurisdiction_settlements=["Вишгород", "Славутич", "Іванків", "Димер", "Поліський район"]),
    Court(id="kv-obukhiv", name="Обухівський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Обухівський район",
          address="м. Обухів, вул. Київська, 18", phone="(04572) 5-56-78",
          jurisdiction_settlements=["Обухів", "Українка", "Кагарлик", "Миронівка", "Ржищів"]),
    Court(id="kv-fastiv", name="Фастівський міськрайонний суд Київської області", court_type="city",
          oblast="Київська область", district="Фастівський район",
          address="м. Фастів, вул. Соборна, 14", phone="(04565) 4-67-89",
          jurisdiction_settlements=["Фастів", "Васильків", "Володарка", "Сквира"]),

    # ================================================================
    # ВІННИЦЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="vn-vinnytsia", name="Вінницький міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Вінницький район",
          address="м. Вінниця, вул. Хмельницьке шосе, 7", phone="(0432) 35-12-34",
          jurisdiction_settlements=["Вінниця", "Вінницький район"]),
    Court(id="vn-bar", name="Барський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Барський район",
          address="м. Бар, вул. Соборна, 1", phone="(04341) 2-12-34",
          jurisdiction_settlements=["Бар", "Шаргород"]),
    Court(id="vn-bershad", name="Бершадський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Бершадський район",
          address="м. Бершадь, вул. Соборна, 4", phone="(04352) 2-23-45",
          jurisdiction_settlements=["Бершадь", "Чечельник", "Ободівка"]),
    Court(id="vn-gaisin", name="Гайсинський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Гайсинський район",
          address="м. Гайсин, вул. Соборна, 30", phone="(04334) 2-34-56",
          jurisdiction_settlements=["Гайсин", "Теплик", "Ладижин"]),
    Court(id="vn-zhmerynka", name="Жмеринський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Жмеринський район",
          address="м. Жмеринка, вул. Соборна, 11", phone="(04332) 3-45-67",
          jurisdiction_settlements=["Жмеринка", "Браїлів", "П'ятничани"]),
    Court(id="vn-koziatyn", name="Козятинський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Козятинський район",
          address="м. Козятин, вул. Героїв Небесної Сотні, 3", phone="(04342) 2-56-78",
          jurisdiction_settlements=["Козятин", "Погребище"]),
    Court(id="vn-mohyliv", name="Могилів-Подільський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Могилів-Подільський район",
          address="м. Могилів-Подільський, вул. Стефана Баторія, 6", phone="(04337) 2-67-89",
          jurisdiction_settlements=["Могилів-Подільський", "Ямпіль", "Крижопіль", "Піщанка"]),
    Court(id="vn-nemyriv", name="Немирівський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Немирівський район",
          address="м. Немирів, вул. Шевченка, 2", phone="(04331) 2-78-90",
          jurisdiction_settlements=["Немирів", "Липовець", "Іллінці"]),
    Court(id="vn-tulchyn", name="Тульчинський міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Тульчинський район",
          address="м. Тульчин, вул. Леніна, 18", phone="(04335) 2-89-01",
          jurisdiction_settlements=["Тульчин", "Томашпіль", "Тростянець"]),
    Court(id="vn-khmilnyk", name="Хмільницький міськрайонний суд Вінницької області", court_type="city",
          oblast="Вінницька область", district="Хмільницький район",
          address="м. Хмільник, вул. Соборна, 10", phone="(04338) 2-90-12",
          jurisdiction_settlements=["Хмільник", "Літин", "Оратів"]),

    # ================================================================
    # ВОЛИНСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="vl-lutsk", name="Луцький міськрайонний суд Волинської області", court_type="city",
          oblast="Волинська область", district="Луцький район",
          address="м. Луцьк, вул. Кривий Вал, 31", phone="(0332) 72-12-34",
          jurisdiction_settlements=["Луцьк", "Рожище", "Ківерці"]),
    Court(id="vl-volodymyr", name="Володимирський міськрайонний суд Волинської області", court_type="city",
          oblast="Волинська область", district="Володимирський район",
          address="м. Володимир, вул. Луцька, 40", phone="(03342) 2-23-45",
          jurisdiction_settlements=["Володимир", "Нововолинськ", "Іваничі", "Горохів", "Локачі"]),
    Court(id="vl-kovel", name="Ковельський міськрайонний суд Волинської області", court_type="city",
          oblast="Волинська область", district="Ковельський район",
          address="м. Ковель, вул. Незалежності, 73", phone="(03352) 5-34-56",
          jurisdiction_settlements=["Ковель", "Турійськ", "Ратне", "Стара Вижівка", "Любомль"]),
    Court(id="vl-kamin-kashir", name="Камінь-Каширський міськрайонний суд Волинської області", court_type="city",
          oblast="Волинська область", district="Камінь-Каширський район",
          address="м. Камінь-Каширський, вул. Шевченка, 12", phone="(03357) 2-45-67",
          jurisdiction_settlements=["Камінь-Каширський", "Маневичі", "Любешів", "Шацьк"]),

    # ================================================================
    # ДНІПРОПЕТРОВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="dp-dnipro-tsentralny", name="Центральний районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, просп. Яворницького, 57", phone="(056) 374-12-34",
          jurisdiction_settlements=["Дніпро (Центральний район)"]),
    Court(id="dp-dnipro-sobor", name="Соборний районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, просп. Гагаріна, 73", phone="(056) 374-23-45",
          jurisdiction_settlements=["Дніпро (Соборний район)"]),
    Court(id="dp-dnipro-checher", name="Чечелівський районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Героїв Січі, 9", phone="(056) 374-34-56",
          jurisdiction_settlements=["Дніпро (Чечелівський район)"]),
    Court(id="dp-dnipro-samar", name="Самарський районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Електрична, 1а", phone="(056) 374-45-67",
          jurisdiction_settlements=["Дніпро (Самарський район)"]),
    Court(id="dp-dnipro-amur", name="Амур-Нижньодніпровський районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Новоселівська, 9", phone="(056) 374-56-78",
          jurisdiction_settlements=["Дніпро (Амур-Нижньодніпровський район)"]),
    Court(id="dp-dnipro-indust", name="Індустріальний районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Харківська, 30", phone="(056) 374-67-89",
          jurisdiction_settlements=["Дніпро (Індустріальний район)"]),
    Court(id="dp-dnipro-novokod", name="Новокодацький районний суд м. Дніпропетровська", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Будівельників, 2", phone="(056) 374-78-90",
          jurisdiction_settlements=["Дніпро (Новокодацький район)"]),
    Court(id="dp-kamyanske", name="Кам'янський міськрайонний суд Дніпропетровської області", court_type="city",
          oblast="Дніпропетровська область", district="Кам'янський район",
          address="м. Кам'янське, просп. Свободи, 30", phone="(05692) 6-12-34",
          jurisdiction_settlements=["Кам'янське", "Верхньодніпровськ"]),
    Court(id="dp-kryvyi-rih-1", name="Довгинцівський районний суд м. Кривого Рогу", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Кривий Ріг",
          address="м. Кривий Ріг, вул. Героїв АТО, 51", phone="(056) 404-12-34",
          jurisdiction_settlements=["Кривий Ріг (Довгинцівський район)"]),
    Court(id="dp-kryvyi-rih-2", name="Інгулецький районний суд м. Кривого Рогу", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Кривий Ріг",
          address="м. Кривий Ріг, вул. Інгулецька, 5", phone="(056) 404-23-45",
          jurisdiction_settlements=["Кривий Ріг (Інгулецький район)"]),
    Court(id="dp-kryvyi-rih-3", name="Саксаганський районний суд м. Кривого Рогу", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Кривий Ріг",
          address="м. Кривий Ріг, просп. Гагаріна, 17", phone="(056) 404-34-56",
          jurisdiction_settlements=["Кривий Ріг (Саксаганський район)"]),
    Court(id="dp-kryvyi-rih-4", name="Тернівський районний суд м. Кривого Рогу", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Кривий Ріг",
          address="м. Кривий Ріг, вул. Дніпропетровська, 46", phone="(056) 404-45-67",
          jurisdiction_settlements=["Кривий Ріг (Тернівський район)"]),
    Court(id="dp-kryvyi-rih-5", name="Центрально-Міський районний суд м. Кривого Рогу", court_type="city_district",
          oblast="Дніпропетровська область", district="м. Кривий Ріг",
          address="м. Кривий Ріг, вул. Першотравнева, 12", phone="(056) 404-56-78",
          jurisdiction_settlements=["Кривий Ріг (Центрально-Міський район)"]),
    Court(id="dp-nikopol", name="Нікопольський міськрайонний суд Дніпропетровської області", court_type="city",
          oblast="Дніпропетровська область", district="Нікопольський район",
          address="м. Нікополь, вул. Електрометалургів, 12", phone="(05662) 2-12-34",
          jurisdiction_settlements=["Нікополь", "Марганець", "Покров", "Томаківка"]),
    Court(id="dp-novomoskow", name="Новомосковський міськрайонний суд Дніпропетровської області", court_type="city",
          oblast="Дніпропетровська область", district="Новомосковський район",
          address="м. Новомосковськ, вул. Гетьманська, 12", phone="(05693) 7-23-45",
          jurisdiction_settlements=["Новомосковськ", "Магдалинівка", "Петриківка", "Юр'ївка"]),
    Court(id="dp-pavlograd", name="Павлоградський міськрайонний суд Дніпропетровської області", court_type="city",
          oblast="Дніпропетровська область", district="Павлоградський район",
          address="м. Павлоград, вул. Дніпровська, 135", phone="(05632) 6-34-56",
          jurisdiction_settlements=["Павлоград", "Тернівка", "Межова", "Петропавлівка"]),
    Court(id="dp-synelnyk", name="Синельниківський міськрайонний суд Дніпропетровської області", court_type="city",
          oblast="Дніпропетровська область", district="Синельниківський район",
          address="м. Синельникове, вул. Миру, 30", phone="(05663) 4-45-67",
          jurisdiction_settlements=["Синельникове", "Васильківка", "Царичанка"]),

    # ================================================================
    # ДОНЕЦЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="dn-kramatorsk", name="Краматорський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="Краматорський район",
          address="м. Краматорськ, вул. Героїв Небесної Сотні, 2", phone="(0626) 41-12-34",
          jurisdiction_settlements=["Краматорськ", "Дружківка", "Костянтинівка", "Лиман"]),
    Court(id="dn-mariupol", name="Маріупольський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="м. Маріуполь",
          address="м. Маріуполь, просп. Миру, 40", phone="(0629) 33-12-34",
          jurisdiction_settlements=["Маріуполь", "Мангуш", "Нікольське"]),
    Court(id="dn-pokrovsk", name="Покровський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="Покровський район",
          address="м. Покровськ, вул. Європейська, 64", phone="(06239) 2-23-45",
          jurisdiction_settlements=["Покровськ", "Мирноград", "Добропілля", "Селидове"]),
    Court(id="dn-slovyansk", name="Слов'янський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="Слов'янський район",
          address="м. Слов'янськ, вул. Батюка, 24", phone="(06262) 2-34-56",
          jurisdiction_settlements=["Слов'янськ", "Святогірськ", "Ізюм"]),
    Court(id="dn-bakhmut", name="Бахмутський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="Бахмутський район",
          address="м. Бахмут, вул. Миру, 47", phone="(06274) 4-45-67",
          jurisdiction_settlements=["Бахмут", "Соледар", "Часів Яр", "Сіверськ"]),
    Court(id="dn-volnovakha", name="Волноваський міськрайонний суд Донецької області", court_type="city",
          oblast="Донецька область", district="Волноваський район",
          address="м. Волноваха, вул. Центральна, 16", phone="(06244) 4-56-78",
          jurisdiction_settlements=["Волноваха", "Великоновосілківське", "Мар'їнка"]),

    # ================================================================
    # ЖИТОМИРСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="zt-zhytomyr", name="Житомирський міськрайонний суд Житомирської області", court_type="city",
          oblast="Житомирська область", district="Житомирський район",
          address="м. Житомир, вул. Велика Бердичівська, 16", phone="(0412) 47-12-34",
          jurisdiction_settlements=["Житомир", "Чуднів"]),
    Court(id="zt-berdychiv", name="Бердичівський міськрайонний суд Житомирської області", court_type="city",
          oblast="Житомирська область", district="Бердичівський район",
          address="м. Бердичів, вул. Європейська, 39", phone="(04143) 2-23-45",
          jurisdiction_settlements=["Бердичів", "Андрушівка", "Червоне"]),
    Court(id="zt-korosten", name="Коростенський міськрайонний суд Житомирської області", court_type="city",
          oblast="Житомирська область", district="Коростенський район",
          address="м. Коростень, вул. Грушевського, 22", phone="(04142) 4-34-56",
          jurisdiction_settlements=["Коростень", "Лугини", "Овруч", "Олевськ", "Народичі"]),
    Court(id="zt-novograd", name="Новоград-Волинський міськрайонний суд Житомирської області", court_type="city",
          oblast="Житомирська область", district="Новоград-Волинський район",
          address="м. Новоград-Волинський, вул. Шевченка, 10", phone="(04141) 5-45-67",
          jurisdiction_settlements=["Новоград-Волинський", "Баранівка", "Ємільчине", "Довбиш"]),
    Court(id="zt-malyn", name="Малинський міськрайонний суд Житомирської області", court_type="city",
          oblast="Житомирська область", district="Малинський район",
          address="м. Малин, вул. Соборна, 2", phone="(04133) 2-56-78",
          jurisdiction_settlements=["Малин", "Радомишль", "Коростишів"]),

    # ================================================================
    # ЗАКАРПАТСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="zk-uzhgorod", name="Ужгородський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Ужгородський район",
          address="м. Ужгород, вул. Собранецька, 10", phone="(0312) 61-12-34",
          jurisdiction_settlements=["Ужгород", "Перечин", "Великий Березний"]),
    Court(id="zk-mukachevo", name="Мукачівський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Мукачівський район",
          address="м. Мукачево, вул. Мира, 26", phone="(03131) 2-23-45",
          jurisdiction_settlements=["Мукачево", "Свалява", "Воловець", "Міжгір'я"]),
    Court(id="zk-beregovo", name="Берегівський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Берегівський район",
          address="м. Берегове, вул. Мукачівська, 2", phone="(03141) 2-34-56",
          jurisdiction_settlements=["Берегове", "Виноградів", "Вилок"]),
    Court(id="zk-khust", name="Хустський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Хустський район",
          address="м. Хуст, вул. Карпатська, 1", phone="(03142) 4-45-67",
          jurisdiction_settlements=["Хуст", "Іршава", "Міжгір'я"]),
    Court(id="zk-tiachiv", name="Тячівський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Тячівський район",
          address="м. Тячів, вул. Незалежності, 9", phone="(03134) 2-56-78",
          jurisdiction_settlements=["Тячів", "Солотвино", "Вільхівці"]),
    Court(id="zk-rakhiv", name="Рахівський міськрайонний суд Закарпатської області", court_type="city",
          oblast="Закарпатська область", district="Рахівський район",
          address="м. Рахів, вул. Миру, 15", phone="(03132) 2-67-89",
          jurisdiction_settlements=["Рахів", "Великий Бичків", "Ясіня"]),

    # ================================================================
    # ЗАПОРІЗЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="zp-zaporiz-1", name="Запорізький районний суд Запорізької області", court_type="city_district",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, просп. Соборний, 160", phone="(061) 224-12-34",
          jurisdiction_settlements=["Запоріжжя (Запорізький район)"]),
    Court(id="zp-zaporiz-2", name="Олександрівський районний суд м. Запоріжжя", court_type="city_district",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, вул. Перемоги, 28", phone="(061) 224-23-45",
          jurisdiction_settlements=["Запоріжжя (Олександрівський район)"]),
    Court(id="zp-zaporiz-3", name="Вознесенівський районний суд м. Запоріжжя", court_type="city_district",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, вул. Північне шосе, 18", phone="(061) 224-34-56",
          jurisdiction_settlements=["Запоріжжя (Вознесенівський район)"]),
    Court(id="zp-zaporiz-4", name="Хортицький районний суд м. Запоріжжя", court_type="city_district",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, вул. Передова, 4", phone="(061) 224-45-67",
          jurisdiction_settlements=["Запоріжжя (Хортицький район)"]),
    Court(id="zp-berdyansk", name="Бердянський міськрайонний суд Запорізької області", court_type="city",
          oblast="Запорізька область", district="Бердянський район",
          address="м. Бердянськ, просп. Перемоги, 2", phone="(06153) 8-56-78",
          jurisdiction_settlements=["Бердянськ", "Приморськ", "Якимівка"]),
    Court(id="zp-melitopol", name="Мелітопольський міськрайонний суд Запорізької області", court_type="city",
          oblast="Запорізька область", district="Мелітопольський район",
          address="м. Мелітополь, вул. Гетьманська, 33", phone="(0619) 42-67-89",
          jurisdiction_settlements=["Мелітополь", "Токмак", "Пологи", "Оріхів", "Вільнянськ"]),

    # ================================================================
    # ІВАНО-ФРАНКІВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="if-ivfrank", name="Івано-Франківський міськрайонний суд Івано-Франківської області", court_type="city",
          oblast="Івано-Франківська область", district="Івано-Франківський район",
          address="м. Івано-Франківськ, вул. Шевченка, 11", phone="(0342) 75-12-34",
          jurisdiction_settlements=["Івано-Франківськ", "Тисмениця", "Тлумач"]),
    Court(id="if-kalush", name="Калуський міськрайонний суд Івано-Франківської області", court_type="city",
          oblast="Івано-Франківська область", district="Калуський район",
          address="м. Калуш, вул. Героїв Майдану, 14", phone="(03472) 6-23-45",
          jurisdiction_settlements=["Калуш", "Долина", "Болехів", "Рожнятів"]),
    Court(id="if-kolomyia", name="Коломийський міськрайонний суд Івано-Франківської області", court_type="city",
          oblast="Івано-Франківська область", district="Коломийський район",
          address="м. Коломия, вул. Грушевського, 50", phone="(03433) 2-34-56",
          jurisdiction_settlements=["Коломия", "Городенка", "Снятин", "Косів", "Верховина"]),
    Court(id="if-nadvirna", name="Надвірнянський міськрайонний суд Івано-Франківської області", court_type="city",
          oblast="Івано-Франківська область", district="Надвірнянський район",
          address="м. Надвірна, вул. Грушевського, 30", phone="(03475) 2-45-67",
          jurisdiction_settlements=["Надвірна", "Яремче", "Ворохта", "Делятин"]),

    # ================================================================
    # КІРОВОГРАДСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="kr-kropyvn", name="Кропивницький міськрайонний суд Кіровоградської області", court_type="city",
          oblast="Кіровоградська область", district="Кропивницький район",
          address="м. Кропивницький, вул. Дворцова, 4", phone="(0522) 22-12-34",
          jurisdiction_settlements=["Кропивницький", "Бобринець"]),
    Court(id="kr-oleksandr", name="Олександрійський міськрайонний суд Кіровоградської області", court_type="city",
          oblast="Кіровоградська область", district="Олександрійський район",
          address="м. Олександрія, вул. Героїв, 15", phone="(05235) 7-23-45",
          jurisdiction_settlements=["Олександрія", "Знам'янка", "Світловодськ", "Петрове"]),
    Court(id="kr-novoukkr", name="Новоукраїнський міськрайонний суд Кіровоградської області", court_type="city",
          oblast="Кіровоградська область", district="Новоукраїнський район",
          address="м. Новоукраїнка, вул. Соборна, 12", phone="(05234) 2-34-56",
          jurisdiction_settlements=["Новоукраїнка", "Помічна", "Гайворон", "Голованівськ"]),

    # ================================================================
    # ЛУГАНСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="lg-sievierod", name="Сєвєродонецький міськрайонний суд Луганської області", court_type="city",
          oblast="Луганська область", district="Сєвєродонецький район",
          address="м. Сєвєродонецьк, вул. Донецька, 31", phone="(06452) 4-12-34",
          jurisdiction_settlements=["Сєвєродонецьк", "Лисичанськ", "Рубіжне", "Кремінна"]),
    Court(id="lg-starobilsk", name="Старобільський міськрайонний суд Луганської області", court_type="city",
          oblast="Луганська область", district="Старобільський район",
          address="м. Старобільськ, вул. Шевченка, 10", phone="(06461) 2-23-45",
          jurisdiction_settlements=["Старобільськ", "Біловодськ", "Сватове", "Троїцьке"]),
    Court(id="lg-shchastia", name="Щастинський міськрайонний суд Луганської області", court_type="city",
          oblast="Луганська область", district="Щастинський район",
          address="м. Щастя, вул. Миру, 22", phone="(06473) 2-34-56",
          jurisdiction_settlements=["Щастя", "Новоайдар", "Станиця Луганська"]),

    # ================================================================
    # ЛЬВІВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="lv-galytsk", name="Галицький районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Князя Романа, 1", phone="(032) 261-12-34",
          jurisdiction_settlements=["Львів (Галицький район)"]),
    Court(id="lv-zalizn", name="Залізничний районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Угорська, 5", phone="(032) 233-23-45",
          jurisdiction_settlements=["Львів (Залізничний район)"]),
    Court(id="lv-lychakiv", name="Личаківський районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Мечникова, 16", phone="(032) 276-34-56",
          jurisdiction_settlements=["Львів (Личаківський район)"]),
    Court(id="lv-sykhiv", name="Сихівський районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Зелена, 149", phone="(032) 244-45-67",
          jurisdiction_settlements=["Львів (Сихівський район)"]),
    Court(id="lv-frankiv", name="Франківський районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Кн. Ольги, 7", phone="(032) 238-56-78",
          jurisdiction_settlements=["Львів (Франківський район)"]),
    Court(id="lv-shevch", name="Шевченківський районний суд міста Львова", court_type="city_district",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Котляревського, 12", phone="(032) 233-67-89",
          jurisdiction_settlements=["Львів (Шевченківський район)"]),
    Court(id="lv-drohobych", name="Дрогобицький міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Дрогобицький район",
          address="м. Дрогобич, вул. Грушевського, 2", phone="(03244) 2-12-34",
          jurisdiction_settlements=["Дрогобич", "Трускавець", "Борислав", "Стебник"]),
    Court(id="lv-chervonogr", name="Червоноградський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Червоноградський район",
          address="м. Червоноград, вул. Шевченка, 20", phone="(03249) 3-23-45",
          jurisdiction_settlements=["Червоноград", "Сокаль", "Радехів", "Белз"]),
    Court(id="lv-sambir", name="Самбірський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Самбірський район",
          address="м. Самбір, вул. Мазепи, 16", phone="(03236) 2-34-56",
          jurisdiction_settlements=["Самбір", "Турка", "Старий Самбір", "Борислав"]),
    Court(id="lv-stryi", name="Стрийський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Стрийський район",
          address="м. Стрий, вул. Шевченка, 59", phone="(03245) 5-45-67",
          jurisdiction_settlements=["Стрий", "Моршин", "Сколе", "Жидачів"]),
    Court(id="lv-zolochiv", name="Золочівський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Золочівський район",
          address="м. Золочів, вул. Шашкевича, 3", phone="(03265) 2-56-78",
          jurisdiction_settlements=["Золочів", "Броди", "Буськ", "Перемишляни"]),
    Court(id="lv-yavoriv", name="Яворівський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Яворівський район",
          address="м. Яворів, вул. Шевченка, 41", phone="(03259) 2-67-89",
          jurisdiction_settlements=["Яворів", "Новояворівськ", "Городок", "Мостиська"]),
    Court(id="lv-zhovkva", name="Жовківський міськрайонний суд Львівської області", court_type="city",
          oblast="Львівська область", district="Жовківський район",
          address="м. Жовква, вул. Львівська, 25", phone="(03252) 2-78-90",
          jurisdiction_settlements=["Жовква", "Рава-Руська", "Кам'янка-Бузька"]),

    # ================================================================
    # МИКОЛАЇВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="mk-mykolaiv-1", name="Центральний районний суд м. Миколаєва", court_type="city_district",
          oblast="Миколаївська область", district="м. Миколаїв",
          address="м. Миколаїв, вул. 6-а Слобідська, 35", phone="(0512) 47-12-34",
          jurisdiction_settlements=["Миколаїв (Центральний район)"]),
    Court(id="mk-mykolaiv-2", name="Корабельний районний суд м. Миколаєва", court_type="city_district",
          oblast="Миколаївська область", district="м. Миколаїв",
          address="м. Миколаїв, просп. Богоявленський, 300", phone="(0512) 47-23-45",
          jurisdiction_settlements=["Миколаїв (Корабельний район)"]),
    Court(id="mk-mykolaiv-3", name="Заводський районний суд м. Миколаєва", court_type="city_district",
          oblast="Миколаївська область", district="м. Миколаїв",
          address="м. Миколаїв, вул. Генерала Карпенка, 15", phone="(0512) 47-34-56",
          jurisdiction_settlements=["Миколаїв (Заводський район)"]),
    Court(id="mk-voznesensk", name="Вознесенський міськрайонний суд Миколаївської області", court_type="city",
          oblast="Миколаївська область", district="Вознесенський район",
          address="м. Вознесенськ, вул. Соборна, 28", phone="(05134) 3-45-67",
          jurisdiction_settlements=["Вознесенськ", "Южноукраїнськ", "Первомайськ", "Арбузинка"]),
    Court(id="mk-bashtanka", name="Баштанський міськрайонний суд Миколаївської області", court_type="city",
          oblast="Миколаївська область", district="Баштанський район",
          address="м. Баштанка, вул. Незалежності, 1", phone="(05158) 2-56-78",
          jurisdiction_settlements=["Баштанка", "Новий Буг", "Очаків", "Снігурівка"]),

    # ================================================================
    # ОДЕСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="od-kyivsk", name="Київський районний суд м. Одеси", court_type="city_district",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Фонтанська дорога, 14", phone="(048) 723-12-34",
          jurisdiction_settlements=["Одеса (Київський район)"]),
    Court(id="od-malynov", name="Малиновський районний суд м. Одеси", court_type="city_district",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Героїв Оборони Одеси, 33", phone="(048) 723-23-45",
          jurisdiction_settlements=["Одеса (Малиновський район)"]),
    Court(id="od-primorsk", name="Приморський районний суд м. Одеси", court_type="city_district",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Черняховського, 12", phone="(048) 728-34-56",
          jurisdiction_settlements=["Одеса (Приморський район)"]),
    Court(id="od-suvorov", name="Суворовський районний суд м. Одеси", court_type="city_district",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Космонавтів, 4", phone="(048) 766-45-67",
          jurisdiction_settlements=["Одеса (Суворовський район)"]),
    Court(id="od-bilgor-dnistr", name="Білгород-Дністровський міськрайонний суд Одеської області", court_type="city",
          oblast="Одеська область", district="Білгород-Дністровський район",
          address="м. Білгород-Дністровський, вул. Кутузова, 10", phone="(04849) 2-56-78",
          jurisdiction_settlements=["Білгород-Дністровський", "Затока", "Сергіївка"]),
    Court(id="od-izmail", name="Ізмаїльський міськрайонний суд Одеської області", court_type="city",
          oblast="Одеська область", district="Ізмаїльський район",
          address="м. Ізмаїл, просп. Миру, 21", phone="(04841) 2-67-89",
          jurisdiction_settlements=["Ізмаїл", "Болград", "Рені", "Кілія", "Арциз"]),
    Court(id="od-rozdilna", name="Роздільнянський міськрайонний суд Одеської області", court_type="city",
          oblast="Одеська область", district="Роздільнянський район",
          address="м. Роздільна, вул. Першотравнева, 14", phone="(04853) 2-78-90",
          jurisdiction_settlements=["Роздільна", "Ананьїв", "Балта", "Кодима"]),
    Court(id="od-podilsk", name="Подільський міськрайонний суд Одеської області", court_type="city",
          oblast="Одеська область", district="Подільський район",
          address="м. Подільськ, вул. Соборна, 7", phone="(04862) 3-89-01",
          jurisdiction_settlements=["Подільськ", "Любашівка", "Савранський район"]),
    Court(id="od-ovidiopol", name="Овідіопольський міськрайонний суд Одеської області", court_type="city",
          oblast="Одеська область", district="Овідіопольський район",
          address="смт. Овідіополь, вул. Шевченка, 2", phone="(04864) 2-90-12",
          jurisdiction_settlements=["Овідіополь", "Чорноморськ", "Южне", "Теплодар"]),

    # ================================================================
    # ПОЛТАВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="pl-poltava-1", name="Октябрський районний суд м. Полтави", court_type="city_district",
          oblast="Полтавська область", district="м. Полтава",
          address="м. Полтава, вул. Європейська, 4", phone="(0532) 56-12-34",
          jurisdiction_settlements=["Полтава (Октябрський район)"]),
    Court(id="pl-poltava-2", name="Київський районний суд м. Полтави", court_type="city_district",
          oblast="Полтавська область", district="м. Полтава",
          address="м. Полтава, вул. Соборності, 36", phone="(0532) 56-23-45",
          jurisdiction_settlements=["Полтава (Київський район)"]),
    Court(id="pl-poltava-3", name="Ленінський районний суд м. Полтави", court_type="city_district",
          oblast="Полтавська область", district="м. Полтава",
          address="м. Полтава, вул. Пушкіна, 8", phone="(0532) 56-34-56",
          jurisdiction_settlements=["Полтава (Ленінський район)"]),
    Court(id="pl-kremenchuk", name="Кременчуцький міськрайонний суд Полтавської області", court_type="city",
          oblast="Полтавська область", district="Кременчуцький район",
          address="м. Кременчук, вул. Лейтенанта Покладова, 4", phone="(0536) 74-45-67",
          jurisdiction_settlements=["Кременчук", "Горішні Плавні", "Глобине"]),
    Court(id="pl-myrgorod", name="Миргородський міськрайонний суд Полтавської області", court_type="city",
          oblast="Полтавська область", district="Миргородський район",
          address="м. Миргород, вул. Гоголя, 112", phone="(05355) 4-56-78",
          jurisdiction_settlements=["Миргород", "Хорол", "Велика Багачка", "Гадяч"]),
    Court(id="pl-lubny", name="Лубенський міськрайонний суд Полтавської області", court_type="city",
          oblast="Полтавська область", district="Лубенський район",
          address="м. Лубни, вул. Монастирська, 7", phone="(05361) 7-67-89",
          jurisdiction_settlements=["Лубни", "Пирятин", "Чорнухи", "Оржиця"]),

    # ================================================================
    # РІВНЕНСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="rv-rivne", name="Рівненський міськрайонний суд Рівненської області", court_type="city",
          oblast="Рівненська область", district="Рівненський район",
          address="м. Рівне, вул. Корольова, 4", phone="(0362) 63-12-34",
          jurisdiction_settlements=["Рівне", "Здолбунів", "Радивилів", "Острог"]),
    Court(id="rv-dubno", name="Дубенський міськрайонний суд Рівненської області", court_type="city",
          oblast="Рівненська область", district="Дубенський район",
          address="м. Дубно, вул. Шевченка, 3", phone="(03656) 2-23-45",
          jurisdiction_settlements=["Дубно", "Млинів", "Демидівка"]),
    Court(id="rv-kostopil", name="Костопільський міськрайонний суд Рівненської області", court_type="city",
          oblast="Рівненська область", district="Костопільський район",
          address="м. Костопіль, вул. Грушевського, 8", phone="(03657) 2-34-56",
          jurisdiction_settlements=["Костопіль", "Березне", "Деражне"]),
    Court(id="rv-sarny", name="Сарненський міськрайонний суд Рівненської області", court_type="city",
          oblast="Рівненська область", district="Сарненський район",
          address="м. Сарни, вул. Б. Хмельницького, 17", phone="(03655) 3-45-67",
          jurisdiction_settlements=["Сарни", "Рокитне", "Дубровиця", "Володимирець"]),

    # ================================================================
    # СУМСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="sm-sumy-1", name="Зарічний районний суд м. Суми", court_type="city_district",
          oblast="Сумська область", district="м. Суми",
          address="м. Суми, вул. Герасима Кондратьєва, 28", phone="(0542) 66-12-34",
          jurisdiction_settlements=["Суми (Зарічний район)"]),
    Court(id="sm-sumy-2", name="Ковпаківський районний суд м. Суми", court_type="city_district",
          oblast="Сумська область", district="м. Суми",
          address="м. Суми, вул. Кооперативна, 2", phone="(0542) 66-23-45",
          jurisdiction_settlements=["Суми (Ковпаківський район)"]),
    Court(id="sm-konotop", name="Конотопський міськрайонний суд Сумської області", court_type="city",
          oblast="Сумська область", district="Конотопський район",
          address="м. Конотоп, вул. Перемоги, 7", phone="(05447) 2-34-56",
          jurisdiction_settlements=["Конотоп", "Кролевець", "Буринь", "Путивль"]),
    Court(id="sm-shostka", name="Шосткинський міськрайонний суд Сумської області", court_type="city",
          oblast="Сумська область", district="Шосткинський район",
          address="м. Шостка, вул. Свободи, 28", phone="(05449) 4-45-67",
          jurisdiction_settlements=["Шостка", "Глухів", "Середина-Буда", "Ямпіль"]),
    Court(id="sm-okhtyrka", name="Охтирський міськрайонний суд Сумської області", court_type="city",
          oblast="Сумська область", district="Охтирський район",
          address="м. Охтирка, вул. Петропавлівська, 15", phone="(05446) 4-56-78",
          jurisdiction_settlements=["Охтирка", "Тростянець", "Лебедин", "Недригайлів"]),
    Court(id="sm-romny", name="Роменський міськрайонний суд Сумської області", court_type="city",
          oblast="Сумська область", district="Роменський район",
          address="м. Ромни, вул. Соборна, 58", phone="(05448) 2-67-89",
          jurisdiction_settlements=["Ромни", "Липова Долина", "Талалаївка"]),

    # ================================================================
    # ТЕРНОПІЛЬСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="te-ternopil", name="Тернопільський міськрайонний суд Тернопільської області", court_type="city",
          oblast="Тернопільська область", district="Тернопільський район",
          address="м. Тернопіль, вул. Грушевського, 2", phone="(0352) 25-12-34",
          jurisdiction_settlements=["Тернопіль", "Зборів", "Підволочиськ", "Теребовля"]),
    Court(id="te-kremenets", name="Кременецький міськрайонний суд Тернопільської області", court_type="city",
          oblast="Тернопільська область", district="Кременецький район",
          address="м. Кременець, вул. Шевченка, 74", phone="(03546) 2-23-45",
          jurisdiction_settlements=["Кременець", "Шумськ", "Лановці", "Вишнівець"]),
    Court(id="te-chortkiv", name="Чортківський міськрайонний суд Тернопільської області", court_type="city",
          oblast="Тернопільська область", district="Чортківський район",
          address="м. Чортків, вул. Шевченка, 11", phone="(03552) 2-34-56",
          jurisdiction_settlements=["Чортків", "Борщів", "Заліщики", "Бучач", "Монастириська", "Гусятин"]),

    # ================================================================
    # ХАРКІВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="kh-kyivsk", name="Київський районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Пушкінська, 5", phone="(057) 700-12-34",
          jurisdiction_settlements=["Харків (Київський район)"]),
    Court(id="kh-nemysh", name="Немишлянський районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Шевченка, 30", phone="(057) 700-23-45",
          jurisdiction_settlements=["Харків (Немишлянський район)"]),
    Court(id="kh-osnovyan", name="Основ'янський районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Основ'янська, 4", phone="(057) 732-34-56",
          jurisdiction_settlements=["Харків (Основ'янський район)"]),
    Court(id="kh-slobid", name="Слобідський районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Полтавський Шлях, 35", phone="(057) 700-45-67",
          jurisdiction_settlements=["Харків (Слобідський район)"]),
    Court(id="kh-industr", name="Індустріальний районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Фрунзе, 6", phone="(057) 700-56-78",
          jurisdiction_settlements=["Харків (Індустріальний район)"]),
    Court(id="kh-kholod", name="Холодногірський районний суд м. Харкова", court_type="city_district",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Полтавський Шлях, 65", phone="(057) 700-67-89",
          jurisdiction_settlements=["Харків (Холодногірський район)"]),
    Court(id="kh-chuguiv", name="Чугуївський міськрайонний суд Харківської області", court_type="city",
          oblast="Харківська область", district="Чугуївський район",
          address="м. Чугуїв, вул. Харківська, 50", phone="(05746) 2-78-90",
          jurisdiction_settlements=["Чугуїв", "Вовчанськ", "Дергачі", "Золочів"]),
    Court(id="kh-izium", name="Ізюмський міськрайонний суд Харківської області", court_type="city",
          oblast="Харківська область", district="Ізюмський район",
          address="м. Ізюм, вул. Соборна, 6", phone="(05743) 2-89-01",
          jurisdiction_settlements=["Ізюм", "Барвінкове", "Балаклія", "Борова"]),
    Court(id="kh-kupyansk", name="Куп'янський міськрайонний суд Харківської області", court_type="city",
          oblast="Харківська область", district="Куп'янський район",
          address="м. Куп'янськ, вул. 1 Травня, 18", phone="(05742) 5-90-12",
          jurisdiction_settlements=["Куп'янськ", "Дворічна", "Шевченкове", "Великий Бурлук"]),
    Court(id="kh-lozova", name="Лозівський міськрайонний суд Харківської області", court_type="city",
          oblast="Харківська область", district="Лозівський район",
          address="м. Лозова, вул. Ярослава Мудрого, 1", phone="(05745) 2-01-23",
          jurisdiction_settlements=["Лозова", "Первомайський", "Близнюки", "Кегичівка"]),
    Court(id="kh-bogodukhiv", name="Богодухівський міськрайонний суд Харківської області", court_type="city",
          oblast="Харківська область", district="Богодухівський район",
          address="м. Богодухів, вул. Грушевського, 1", phone="(05758) 3-12-34",
          jurisdiction_settlements=["Богодухів", "Краснокутськ", "Нововодолазьке", "Валки"]),

    # ================================================================
    # ХЕРСОНСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="ks-kherson-1", name="Херсонський міськрайонний суд Херсонської області", court_type="city",
          oblast="Херсонська область", district="Херсонський район",
          address="м. Херсон, вул. Перекопська, 6", phone="(0552) 42-12-34",
          jurisdiction_settlements=["Херсон", "Олешки", "Гола Пристань", "Білозерка"]),
    Court(id="ks-kakhovka", name="Каховський міськрайонний суд Херсонської області", court_type="city",
          oblast="Херсонська область", district="Каховський район",
          address="м. Каховка, вул. Героїв України, 15", phone="(05536) 4-23-45",
          jurisdiction_settlements=["Каховка", "Нова Каховка", "Таврійськ", "Берислав", "Великолепетиський район"]),
    Court(id="ks-genichsk", name="Генічеський міськрайонний суд Херсонської області", court_type="city",
          oblast="Херсонська область", district="Генічеський район",
          address="м. Генічеськ, вул. Соборна, 18", phone="(05534) 2-34-56",
          jurisdiction_settlements=["Генічеськ", "Скадовськ", "Іванівка"]),

    # ================================================================
    # ХМЕЛЬНИЦЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="km-khmelnytsk", name="Хмельницький міськрайонний суд Хмельницької області", court_type="city",
          oblast="Хмельницька область", district="Хмельницький район",
          address="м. Хмельницький, вул. Грушевського, 69", phone="(0382) 76-12-34",
          jurisdiction_settlements=["Хмельницький", "Красилів", "Деражня", "Летичів"]),
    Court(id="km-kamianets", name="Кам'янець-Подільський міськрайонний суд Хмельницької області", court_type="city",
          oblast="Хмельницька область", district="Кам'янець-Подільський район",
          address="м. Кам'янець-Подільський, вул. Тринітарська, 5", phone="(03849) 2-23-45",
          jurisdiction_settlements=["Кам'янець-Подільський", "Чемерівці", "Нова Ушиця", "Дунаївці"]),
    Court(id="km-shepetivka", name="Шепетівський міськрайонний суд Хмельницької області", court_type="city",
          oblast="Хмельницька область", district="Шепетівський район",
          address="м. Шепетівка, вул. Героїв Небесної Сотні, 13", phone="(03840) 4-34-56",
          jurisdiction_settlements=["Шепетівка", "Славута", "Нетішин", "Полонне", "Ізяслав", "Старокостянтинів"]),

    # ================================================================
    # ЧЕРКАСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="ck-cherkasy-1", name="Придніпровський районний суд м. Черкаси", court_type="city_district",
          oblast="Черкаська область", district="м. Черкаси",
          address="м. Черкаси, бул. Шевченка, 307", phone="(0472) 36-12-34",
          jurisdiction_settlements=["Черкаси (Придніпровський район)"]),
    Court(id="ck-cherkasy-2", name="Соснівський районний суд м. Черкаси", court_type="city_district",
          oblast="Черкаська область", district="м. Черкаси",
          address="м. Черкаси, вул. Одеська, 6", phone="(0472) 36-23-45",
          jurisdiction_settlements=["Черкаси (Соснівський район)"]),
    Court(id="ck-uman", name="Уманський міськрайонний суд Черкаської області", court_type="city",
          oblast="Черкаська область", district="Уманський район",
          address="м. Умань, вул. Європейська, 48", phone="(04744) 4-34-56",
          jurisdiction_settlements=["Умань", "Тальне", "Монастирище", "Маньківка"]),
    Court(id="ck-zolotonosha", name="Золотоніський міськрайонний суд Черкаської області", court_type="city",
          oblast="Черкаська область", district="Золотоніський район",
          address="м. Золотоноша, вул. Шевченка, 35", phone="(04737) 5-45-67",
          jurisdiction_settlements=["Золотоноша", "Канів", "Драбів", "Чорнобай"]),
    Court(id="ck-smila", name="Сміланський міськрайонний суд Черкаської області", court_type="city",
          oblast="Черкаська область", district="Сміланський район",
          address="м. Сміла, вул. Незалежності, 43", phone="(04733) 4-56-78",
          jurisdiction_settlements=["Сміла", "Кам'янка", "Городище", "Шпола", "Ватутіне"]),
    Court(id="ck-chyhyryn", name="Чигиринський міськрайонний суд Черкаської області", court_type="city",
          oblast="Черкаська область", district="Чигиринський район",
          address="м. Чигирин, вул. Грушевського, 12", phone="(04730) 2-67-89",
          jurisdiction_settlements=["Чигирин", "Черкаський район", "Кам'янка"]),

    # ================================================================
    # ЧЕРНІВЕЦЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="cv-chernivtsi-1", name="Першотравневий районний суд м. Чернівці", court_type="city_district",
          oblast="Чернівецька область", district="м. Чернівці",
          address="м. Чернівці, вул. Головна, 20", phone="(0372) 55-12-34",
          jurisdiction_settlements=["Чернівці (Першотравневий район)"]),
    Court(id="cv-chernivtsi-2", name="Садгірський районний суд м. Чернівці", court_type="city_district",
          oblast="Чернівецька область", district="м. Чернівці",
          address="м. Чернівці, вул. Руська, 178", phone="(0372) 55-23-45",
          jurisdiction_settlements=["Чернівці (Садгірський район)"]),
    Court(id="cv-chernivtsi-3", name="Шевченківський районний суд м. Чернівці", court_type="city_district",
          oblast="Чернівецька область", district="м. Чернівці",
          address="м. Чернівці, вул. Кобилянської, 3", phone="(0372) 55-34-56",
          jurisdiction_settlements=["Чернівці (Шевченківський район)"]),
    Court(id="cv-vyzhnyts", name="Вижницький міськрайонний суд Чернівецької області", court_type="city",
          oblast="Чернівецька область", district="Вижницький район",
          address="м. Вижниця, вул. Українська, 65", phone="(03730) 2-45-67",
          jurisdiction_settlements=["Вижниця", "Путила", "Берегомет"]),
    Court(id="cv-dnistrov", name="Дністровський міськрайонний суд Чернівецької області", court_type="city",
          oblast="Чернівецька область", district="Дністровський район",
          address="м. Хотин, вул. Шевченка, 7", phone="(03731) 2-56-78",
          jurisdiction_settlements=["Хотин", "Кельменці", "Сокиряни", "Новодністровськ"]),
    Court(id="cv-glyboka", name="Глибоцький міськрайонний суд Чернівецької області", court_type="city",
          oblast="Чернівецька область", district="Глибоцький район",
          address="смт. Глибока, вул. Шевченка, 2", phone="(03734) 2-67-89",
          jurisdiction_settlements=["Глибока", "Герца", "Заставна", "Кіцмань", "Новоселиця", "Сторожинець"]),

    # ================================================================
    # ЧЕРНІГІВСЬКА ОБЛАСТЬ
    # ================================================================
    Court(id="cn-chernigiv-1", name="Деснянський районний суд м. Чернігова", court_type="city_district",
          oblast="Чернігівська область", district="м. Чернігів",
          address="м. Чернігів, просп. Перемоги, 65", phone="(0462) 67-12-34",
          jurisdiction_settlements=["Чернігів (Деснянський район)"]),
    Court(id="cn-chernigiv-2", name="Новозаводський районний суд м. Чернігова", court_type="city_district",
          oblast="Чернігівська область", district="м. Чернігів",
          address="м. Чернігів, вул. Шевченка, 30", phone="(0462) 67-23-45",
          jurisdiction_settlements=["Чернігів (Новозаводський район)"]),
    Court(id="cn-nizhyn", name="Ніжинський міськрайонний суд Чернігівської області", court_type="city",
          oblast="Чернігівська область", district="Ніжинський район",
          address="м. Ніжин, вул. Гоголя, 5", phone="(04631) 2-34-56",
          jurisdiction_settlements=["Ніжин", "Бобровиця", "Борзна", "Носівка"]),
    Court(id="cn-pryluky", name="Прилуцький міськрайонний суд Чернігівської області", court_type="city",
          oblast="Чернігівська область", district="Прилуцький район",
          address="м. Прилуки, вул. Гірняка, 6", phone="(04637) 3-45-67",
          jurisdiction_settlements=["Прилуки", "Срібне", "Варва", "Талалаївка"]),
    Court(id="cn-novgorsiver", name="Новгород-Сіверський міськрайонний суд Чернігівської області", court_type="city",
          oblast="Чернігівська область", district="Новгород-Сіверський район",
          address="м. Новгород-Сіверський, вул. Шевченка, 1", phone="(04658) 2-56-78",
          jurisdiction_settlements=["Новгород-Сіверський", "Городня", "Семенівка", "Сновськ"]),
    Court(id="cn-koryukivka", name="Корюківський міськрайонний суд Чернігівської області", court_type="city",
          oblast="Чернігівська область", district="Корюківський район",
          address="м. Корюківка, вул. Визволителів, 5", phone="(04657) 2-67-89",
          jurisdiction_settlements=["Корюківка", "Щорс", "Менський район"]),

    # ================================================================
    # АПЕЛЯЦІЙНІ СУДИ
    # ================================================================
    Court(id="appeal-kyiv", name="Київський апеляційний суд", court_type="appeal",
          oblast="м. Київ", district="м. Київ",
          address="м. Київ, вул. Солом'янська, 2а", phone="(044) 205-50-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-lviv", name="Львівський апеляційний суд", court_type="appeal",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Городоцька, 12", phone="(032) 235-60-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-kharkiv", name="Харківський апеляційний суд", court_type="appeal",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Пушкінська, 17", phone="(057) 700-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-odesa", name="Одеський апеляційний суд", court_type="appeal",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Рішельєвська, 37", phone="(048) 705-80-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-dnipro", name="Дніпровський апеляційний суд", court_type="appeal",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Харківська, 7", phone="(056) 374-90-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-zapor", name="Запорізький апеляційний суд", court_type="appeal",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, просп. Соборний, 170", phone="(061) 224-60-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-vinny", name="Вінницький апеляційний суд", court_type="appeal",
          oblast="Вінницька область", district="м. Вінниця",
          address="м. Вінниця, вул. Соборна, 4", phone="(0432) 35-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-zhytomyr", name="Житомирський апеляційний суд", court_type="appeal",
          oblast="Житомирська область", district="м. Житомир",
          address="м. Житомир, вул. Велика Бердичівська, 25", phone="(0412) 47-80-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-ivfrank", name="Івано-Франківський апеляційний суд", court_type="appeal",
          oblast="Івано-Франківська область", district="м. Івано-Франківськ",
          address="м. Івано-Франківськ, вул. Шевченка, 13", phone="(0342) 75-90-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-volyn", name="Волинський апеляційний суд", court_type="appeal",
          oblast="Волинська область", district="м. Луцьк",
          address="м. Луцьк, вул. Кривий Вал, 31", phone="(0332) 72-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-poltava", name="Полтавський апеляційний суд", court_type="appeal",
          oblast="Полтавська область", district="м. Полтава",
          address="м. Полтава, вул. Стрітенська, 37", phone="(0532) 56-80-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-cherkasy", name="Черкаський апеляційний суд", court_type="appeal",
          oblast="Черкаська область", district="м. Черкаси",
          address="м. Черкаси, бул. Шевченка, 250", phone="(0472) 36-90-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-chernihiv", name="Чернігівський апеляційний суд", court_type="appeal",
          oblast="Чернігівська область", district="м. Чернігів",
          address="м. Чернігів, просп. Перемоги, 83", phone="(0462) 67-60-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-rivne", name="Рівненський апеляційний суд", court_type="appeal",
          oblast="Рівненська область", district="м. Рівне",
          address="м. Рівне, вул. Корольова, 6", phone="(0362) 63-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-ternopil", name="Тернопільський апеляційний суд", court_type="appeal",
          oblast="Тернопільська область", district="м. Тернопіль",
          address="м. Тернопіль, вул. Грушевського, 6", phone="(0352) 25-80-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-sumy", name="Сумський апеляційний суд", court_type="appeal",
          oblast="Сумська область", district="м. Суми",
          address="м. Суми, вул. Герасима Кондратьєва, 30", phone="(0542) 66-90-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-khmeln", name="Хмельницький апеляційний суд", court_type="appeal",
          oblast="Хмельницька область", district="м. Хмельницький",
          address="м. Хмельницький, вул. Грушевського, 58", phone="(0382) 76-60-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-kirovogr", name="Кропивницький апеляційний суд", court_type="appeal",
          oblast="Кіровоградська область", district="м. Кропивницький",
          address="м. Кропивницький, вул. Дворцова, 6", phone="(0522) 22-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-mykolaiv", name="Миколаївський апеляційний суд", court_type="appeal",
          oblast="Миколаївська область", district="м. Миколаїв",
          address="м. Миколаїв, вул. 6-а Слобідська, 37", phone="(0512) 47-80-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-kherson", name="Херсонський апеляційний суд", court_type="appeal",
          oblast="Херсонська область", district="м. Херсон",
          address="м. Херсон, вул. Перекопська, 8", phone="(0552) 42-90-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-zakarpatya", name="Закарпатський апеляційний суд", court_type="appeal",
          oblast="Закарпатська область", district="м. Ужгород",
          address="м. Ужгород, вул. Собранецька, 15", phone="(0312) 61-60-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-chernivtsi", name="Чернівецький апеляційний суд", court_type="appeal",
          oblast="Чернівецька область", district="м. Чернівці",
          address="м. Чернівці, вул. Головна, 22", phone="(0372) 55-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-donetsk", name="Донецький апеляційний суд", court_type="appeal",
          oblast="Донецька область", district="м. Краматорськ",
          address="м. Краматорськ, вул. Героїв Небесної Сотні, 4", phone="(0626) 41-70-00",
          jurisdiction_settlements=[]),
    Court(id="appeal-luhansk", name="Луганський апеляційний суд", court_type="appeal",
          oblast="Луганська область", district="м. Сєвєродонецьк",
          address="м. Сєвєродонецьк, вул. Донецька, 33", phone="(06452) 4-80-00",
          jurisdiction_settlements=[]),

    # ================================================================
    # ГОСПОДАРСЬКІ СУДИ
    # ================================================================
    Court(id="com-kyiv", name="Господарський суд міста Києва", court_type="commercial",
          oblast="м. Київ", district="м. Київ",
          address="м. Київ, бул. Шевченка, 33/34", phone="(044) 235-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-kyiv-obl", name="Господарський суд Київської області", court_type="commercial",
          oblast="Київська область", district="м. Київ",
          address="м. Київ, вул. Комінтерну, 16", phone="(044) 235-11-00",
          jurisdiction_settlements=[]),
    Court(id="com-lviv", name="Господарський суд Львівської області", court_type="commercial",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Личаківська, 128", phone="(032) 275-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-odesa", name="Господарський суд Одеської області", court_type="commercial",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Рішельєвська, 22", phone="(048) 705-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-kharkiv", name="Господарський суд Харківської області", court_type="commercial",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Пушкінська, 19", phone="(057) 700-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-dnipro", name="Господарський суд Дніпропетровської області", court_type="commercial",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Харківська, 3", phone="(056) 374-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-zapor", name="Господарський суд Запорізької області", court_type="commercial",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, просп. Соборний, 163", phone="(061) 224-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-vinny", name="Господарський суд Вінницької області", court_type="commercial",
          oblast="Вінницька область", district="м. Вінниця",
          address="м. Вінниця, вул. Хмельницьке шосе, 5", phone="(0432) 35-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-volyn", name="Господарський суд Волинської області", court_type="commercial",
          oblast="Волинська область", district="м. Луцьк",
          address="м. Луцьк, вул. Кривий Вал, 29", phone="(0332) 72-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-zhytomyr", name="Господарський суд Житомирської області", court_type="commercial",
          oblast="Житомирська область", district="м. Житомир",
          address="м. Житомир, вул. Велика Бердичівська, 14", phone="(0412) 47-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-zakarpatya", name="Господарський суд Закарпатської області", court_type="commercial",
          oblast="Закарпатська область", district="м. Ужгород",
          address="м. Ужгород, вул. Собранецька, 8", phone="(0312) 61-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-ivfrank", name="Господарський суд Івано-Франківської області", court_type="commercial",
          oblast="Івано-Франківська область", district="м. Івано-Франківськ",
          address="м. Івано-Франківськ, вул. Шевченка, 7", phone="(0342) 75-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-kirovogr", name="Господарський суд Кіровоградської області", court_type="commercial",
          oblast="Кіровоградська область", district="м. Кропивницький",
          address="м. Кропивницький, вул. Дворцова, 2", phone="(0522) 22-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-luhansk", name="Господарський суд Луганської області", court_type="commercial",
          oblast="Луганська область", district="м. Сєвєродонецьк",
          address="м. Сєвєродонецьк, вул. Донецька, 29", phone="(06452) 4-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-donetsk", name="Господарський суд Донецької області", court_type="commercial",
          oblast="Донецька область", district="м. Краматорськ",
          address="м. Краматорськ, вул. Героїв Небесної Сотні, 6", phone="(0626) 41-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-mykolaiv", name="Господарський суд Миколаївської області", court_type="commercial",
          oblast="Миколаївська область", district="м. Миколаїв",
          address="м. Миколаїв, вул. 6-а Слобідська, 33", phone="(0512) 47-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-poltava", name="Господарський суд Полтавської області", court_type="commercial",
          oblast="Полтавська область", district="м. Полтава",
          address="м. Полтава, вул. Стрітенська, 35", phone="(0532) 56-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-rivne", name="Господарський суд Рівненської області", court_type="commercial",
          oblast="Рівненська область", district="м. Рівне",
          address="м. Рівне, вул. Корольова, 2", phone="(0362) 63-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-sumy", name="Господарський суд Сумської області", court_type="commercial",
          oblast="Сумська область", district="м. Суми",
          address="м. Суми, вул. Герасима Кондратьєва, 26", phone="(0542) 66-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-ternopil", name="Господарський суд Тернопільської області", court_type="commercial",
          oblast="Тернопільська область", district="м. Тернопіль",
          address="м. Тернопіль, вул. Грушевського, 4", phone="(0352) 25-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-kherson", name="Господарський суд Херсонської області", court_type="commercial",
          oblast="Херсонська область", district="м. Херсон",
          address="м. Херсон, вул. Перекопська, 4", phone="(0552) 42-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-khmeln", name="Господарський суд Хмельницької області", court_type="commercial",
          oblast="Хмельницька область", district="м. Хмельницький",
          address="м. Хмельницький, вул. Грушевського, 67", phone="(0382) 76-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-cherkasy", name="Господарський суд Черкаської області", court_type="commercial",
          oblast="Черкаська область", district="м. Черкаси",
          address="м. Черкаси, бул. Шевченка, 248", phone="(0472) 36-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-chernihiv", name="Господарський суд Чернігівської області", court_type="commercial",
          oblast="Чернігівська область", district="м. Чернігів",
          address="м. Чернігів, просп. Перемоги, 81", phone="(0462) 67-10-00",
          jurisdiction_settlements=[]),
    Court(id="com-chernivtsi", name="Господарський суд Чернівецької області", court_type="commercial",
          oblast="Чернівецька область", district="м. Чернівці",
          address="м. Чернівці, вул. Головна, 18", phone="(0372) 55-10-00",
          jurisdiction_settlements=[]),

    # ================================================================
    # ОКРУЖНІ АДМІНІСТРАТИВНІ СУДИ
    # ================================================================
    Court(id="admin-kyiv", name="Київський окружний адміністративний суд", court_type="admin",
          oblast="м. Київ", district="м. Київ",
          address="м. Київ, вул. Командарма Каменєва, 8", phone="(044) 364-20-00",
          jurisdiction_settlements=[]),
    Court(id="admin-lviv", name="Львівський окружний адміністративний суд", court_type="admin",
          oblast="Львівська область", district="м. Львів",
          address="м. Львів, вул. Чоловського, 2", phone="(032) 261-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-odesa", name="Одеський окружний адміністративний суд", court_type="admin",
          oblast="Одеська область", district="м. Одеса",
          address="м. Одеса, вул. Рішельєвська, 40", phone="(048) 705-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-kharkiv", name="Харківський окружний адміністративний суд", court_type="admin",
          oblast="Харківська область", district="м. Харків",
          address="м. Харків, вул. Пушкінська, 22", phone="(057) 700-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-dnipro", name="Дніпропетровський окружний адміністративний суд", court_type="admin",
          oblast="Дніпропетровська область", district="м. Дніпро",
          address="м. Дніпро, вул. Харківська, 5", phone="(056) 374-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-zapor", name="Запорізький окружний адміністративний суд", court_type="admin",
          oblast="Запорізька область", district="м. Запоріжжя",
          address="м. Запоріжжя, просп. Соборний, 165", phone="(061) 224-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-vinny", name="Вінницький окружний адміністративний суд", court_type="admin",
          oblast="Вінницька область", district="м. Вінниця",
          address="м. Вінниця, вул. Хмельницьке шосе, 3", phone="(0432) 35-30-00",
          jurisdiction_settlements=[]),
    Court(id="admin-volyn", name="Волинський окружний адміністративний суд", court_type="admin",
          oblast="Волинська область", district="м. Луцьк",
          address="м. Луцьк, вул. Кривий Вал, 27", phone="(0332) 72-30-00",
          jurisdiction_settlements=[]),

    # ================================================================
    # ВЕРХОВНИЙ СУД
    # ================================================================
    Court(id="supreme-court", name="Верховний Суд", court_type="supreme",
          oblast="м. Київ", district="м. Київ",
          address="м. Київ, вул. Пилипа Орлика, 4-а", phone="(044) 207-35-46",
          email="inbox@supreme.court.gov.ua", website="https://supreme.court.gov.ua/",
          jurisdiction_settlements=[]),
]


class CourtDatabase:
    """Searchable court database."""

    def __init__(self, courts: Optional[List[Court]] = None) -> None:
        self.courts = courts or COURTS_DB

    def search(
        self,
        query: str = "",
        oblast: str = "",
        court_type: str = "",
    ) -> List[Court]:
        results = self.courts
        if oblast:
            oblast_lower = oblast.lower()
            results = [c for c in results if oblast_lower in c.oblast.lower()]
        if court_type:
            results = [c for c in results if c.court_type == court_type]
        if query:
            q = query.lower()
            results = [
                c for c in results
                if q in c.name.lower()
                or q in c.address.lower()
                or q in c.district.lower()
                or any(q in s.lower() for s in c.jurisdiction_settlements)
            ]
        return results

    def find_by_settlement(self, settlement: str) -> List[Court]:
        s = settlement.lower()
        return [
            c for c in self.courts
            if any(s in js.lower() for js in c.jurisdiction_settlements)
            or s in c.district.lower()
            or s in c.name.lower()
        ]

    def find_by_id(self, court_id: str) -> Optional[Court]:
        for c in self.courts:
            if c.id == court_id:
                return c
        return None

    def get_oblasts(self) -> List[str]:
        return sorted(set(c.oblast for c in self.courts))

    def get_types(self) -> List[str]:
        return sorted(set(c.court_type for c in self.courts))

    def stats(self) -> Dict[str, int]:
        by_type: Dict[str, int] = {}
        for c in self.courts:
            label = COURT_TYPES.get(c.court_type, c.court_type)
            by_type[label] = by_type.get(label, 0) + 1
        return by_type

    def to_json(self) -> str:
        return json.dumps(
            [c.to_dict() for c in self.courts],
            ensure_ascii=False,
            indent=2,
        )
